import vazirFont from "@/constants/localFont";
import "@/styles/globals.css";
import { Toaster } from "react-hot-toast";
import Header from "@/components/Header";
import AuthProvier from "@/context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" >
      <body className={`min-h-screen  ${vazirFont.variable} font-sans `}>
        
      
        <Toaster />
    
          <AuthProvier>
            {children}
            </AuthProvier>
      
      </body>
    </html>
  );
}
